# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_auto_20160531_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
