# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_auto_20160531_1714'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teammember',
            table=None,
        ),
    ]
